version: "3.9"

services:
  frontend:
    image: sermalenk/skypro-front:lesson-36
    restart: on-failure
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    image: ${DOCKERHUB_USERNAME}/todolist:latest
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
      - migrations

  migrations:
    image: ${DOCKERHUB_USERNAME}/todolist:latest
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    command: python todolist/manage.py migrate


  postgres:
    image: postgres:12.4-alpine
    restart: on-failure
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
