version: "3.9"

services:
  frontend:
    image: sermalenk/skypro-front:lesson-35
    restart: on-failure
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  api:
    image: ${DOCKERHUB_USERNAME}/todolist:late
    restart: on-failure
    env_file:
      - ./.env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
      - migrations
    volumes:
      - ./todolist/:/opt/todolist

  migrations:
    build:
      context: .
    env_file:
      - ./.env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    command: python todolist/manage.py migrate


  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - ./.env
    healthcheck:
      test: pg_isready -U ${DB_USER}
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
