version: "3.9"

services:
  frontend:
    image: sermalenk/skypro-front:lesson-35
    restart: on-failure
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    image: ${DOCKERHUB_USERNAME}/todolist:latest
    restart: on-failure
    env_file:
      - ./.env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
      - migrations
    volumes:
      - ./todolist/:/opt/todolist

  migrations:
    image: ${DOCKERHUB_USERNAME}/todolist:latest
    env_file:
      - ./.env
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres
    command: python todolist/manage.py migrate


  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: <DB_USER>
      POSTGRES_PASSWORD: <DB_PASSWORD>
      POSTGRES_DB: <DB_NAME>
    healthcheck:
      test: pg_isready -U <DB_USER> -d <DB_NAME>
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
