version: "3.3"

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: todolist
      POSTGRES_DB: todolist
      DATABASE_URL: pqsl:postgresql://localhost:5432/todolist
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_data: